### ISSUE TITLE
Missing Helper

### ISSUE THREAD

**Issue by DonTortuga** [BradCrumb/CakeImageCropResize#2]
Hi,

Here's what I get when I follow the intructions to install the plugin.

Error: ImageHelper could not be found.
Error: Create the class ImageHelper below in file: app/View/Helper/ImageHelper.php

If I move the ImageHelper.php in View/Helper/

I got this:

Fatal error: Class 'Image' not found in /homez.743/florianszp/dev/Repar-hayon/app/app/View/Helper/ImageHelper.php on line 50

I'm a big cakephp pro so if you could update the doc because I'm obviously missing something here.

Thx !

**Comment by nenomaz** [comment]
Hi,

I had the same problem a few weeks ago, and solved it by changing the name of the file containing the helper because of its case-sensitivity. Try to change it, from 'ImageHelper.php' to 'imageHelper.php'.
