### ISSUE TITLE
Giving broken image path when using on localhost

### ISSUE THREAD

**Issue by dashrat** [BradCrumb/CakeImageCropResize#3]
I installed this plugin in my cakephp 2.2.3 project. I havent tested this live but on my localhost i placed an image in app/webroot/img/pic.png path and caliing 
<?php $options = array(
'width'             => 100, 
'height'            => 100,
);
echo $this->Image->resize("pic.png", $options);
?>
in my view file. but its printing &lt;img src="/essorcode/img/" alt=""></code> only , not resized image path. 
Where am i wrong in using this plugin ? what path do i need to pass for image path ?

**Comment by dashrat** [comment]
The problem was there because plugin was unable to find source image path.
I solved the problem by defining a new constant 

if (!defined('IMG_ROOT')) {
    define('IMG_ROOT',WWW_ROOT."img\");
}
in app/webroot/index.php  and then 
replacing   $fullpath = ROOT . $path; 
by  $fullpath = IMG_ROOT . $path; 
near line 23 
in app/Plugin/ImageCropResize/Lib/Image.php

Its giving result as desired. Hope this help to other too who face similar problem in using this plugin.

Thanks for sharing this plugin.

**Comment by BradCrumb** [comment]
Thanks for the input
